server:
  port: 9092
  contextPath: /customer-portal

database:
  service:
    url: http://localhost:9091/database

product:
  service:
    url: http://localhost:9093/product-portal/

spring:
  freemarker:
    cache: false

management:
  security:
    enabled: false
logging:
  level:
    org.springframework.security.web: debug

keycloak:
  configurationFile: classpath:config/keycloak.json